version: '3'

services:
  ingress:
    image: nginx:alpine
    container_name: ingress_front
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
    depends_on:
      - app
      - wrapper
      - mocks
    volumes:
      - ./ingress/nginx-test.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  mocks:
    build:
      context: ./mocks/dynamic
    container_name: mocks
    ports:
      - 8906:8906
    networks:
      - app-network

  wrapper:
    build:
      context: ./wrapper
    container_name: wrapper
    networks:
      - app-network

  app:
    build:
      context: ..
    container_name: app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
