apiVersion: v1
kind: Service
metadata:
  name: <%= normalizedMfeName %>
  labels:
    app: <%= normalizedMfeName %>
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: port-shell-app
  selector:
    app: <%= normalizedMfeName %>
    release: {{ .Release.Name }}
